{
 "title": "ohm_exporter",
 "tags": [
  "prometheus",
  "ohm_exporter",
  "nvidia",
  "amd"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Server",
    "query": {
     "query": "label_values(ohm_cpu_temperature_celsius,instance)"
    }
   },
   {
    "name": "parent_identifier",
    "label": "Disk",
    "query": {
     "query": "label_values(ohm_disk_temperature_celsius{instance=\"$instance\"},parent_identifier)"
    }
   },
   {
    "name": "fanname",
    "label": "Fan",
    "query": {
     "query": "label_values(ohm_mainboard_lpc_fan_percent{instance=\"$instance\",name!~\"Fan Control.*\"},name)"
    }
   },
   {
    "name": "cpuname",
    "label": "Core",
    "query": {
     "query": "label_values(ohm_cpu_load_percent{instance=\"$instance\",name!~\".*Total.*\"},name)"
    }
   },
   {
    "name": "cputempname",
    "label": "CPUTemp",
    "query": {
     "query": "label_values(ohm_cpu_temperature_celsius{instance=\"$instance\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Name",
   "type": "stat",
   "description": "The official product name of the GPU. This is an alphanumeric string. For all products.",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_load_percent{instance=\"$instance\",name=~\".*Total.*\"}",
     "legendFormat": "{{parent_name}}"
    }
   ]
  },
  {
   "title": "Cpu Total",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_load_percent{instance=\"$instance\",name=~\".*Total.*\"}",
     "legendFormat": "[{{parent_name}}] {{name}}"
    }
   ]
  },
  {
   "title": "Cpu Power Draw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_power_watts{instance=\"$instance\",name=~\".*Package.*\"}",
     "legendFormat": "[{{parent_name}}] {{name}}"
    }
   ]
  },
  {
   "title": "Cpu Bus Clock",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_clock_mhz{instance=\"$instance\",name=~\".*Bus.*\"} * 1000000",
     "legendFormat": "[{{parent_name}}] {{name}}"
    }
   ]
  },
  {
   "title": "Cpu Fan (Pump Fan)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_mainboard_lpc_fan_rpm{instance=\"$instance\",name=~\".ystem.*|.*CPU Fan.*\"} ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$cputempname",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4.8, "x": 0, "y": 5 },
   "repeat": "cputempname",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_temperature_celsius{instance=\"$instance\",name=\"$cputempname\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$cpuname",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 9 },
   "repeat": "cpuname",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_load_percent{instance=\"$instance\",name=~\"$cpuname\"}",
     "legendFormat": "[{{parent_name}}] {{name}}"
    }
   ]
  },
  {
   "title": "$cpuname",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "repeat": "cpuname",
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_power_watts{instance=\"$instance\",name=~\"$cpuname\"}",
     "legendFormat": "[{{parent_name}}] {{name}}"
    }
   ]
  },
  {
   "title": "$cpuname",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 17 },
   "repeat": "cpuname",
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_cpu_clock_mhz{instance=\"$instance\",name=~\"$cpuname\"} *1000000",
     "legendFormat": "[{{parent_name}}] {{name}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_load_percent{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Clock Speed",
   "type": "graph",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_clock_mhz{instance=\"$instance\"} *1000000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "graph",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_temperature_celsius{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ohm_cpu_power_watts{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Name",
   "type": "stat",
   "description": "The official product name of the GPU. This is an alphanumeric string. For all products.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_gpu_fan_rpm{instance=\"$instance\"}",
     "legendFormat": "{{parent_name}}"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_gpu_load_percent{instance=\"$instance\",name=~\".*Core.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_gpu_temperature_celsius{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "gauge",
   "description": "The fan speed value is the percent of the product's maximum noise tolerance fan speed that the device's fan is currently intended to run at. This value may exceed 100% in certain cases. Note: The reported speed is the intended fan speed. If the fan is physically blocked and unable to spin, this output will not match the actual fan speed. Many parts do not report fan speeds because they rely on cooling via fans in the surrounding enclosure.\n",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_gpu_fan_percent{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Load %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_gpu_memory_load_percent{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Clock [Mhz]",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_gpu_memory_clock_mhz{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory Allocation %",
   "type": "gauge",
   "description": "Total memory allocated by active contexts / Total installed GPU memory.",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_memory_used_bytes{uuid=\"$gpu\"} / nvidia_smi_memory_total_bytes{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Power Watt",
   "type": "gauge",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts / The software power limit in watts.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_gpu_power_watts{instance=\"$instance\",name=~\".*Power.*|.*Total.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GPU Clock Speed",
   "type": "gauge",
   "description": "\n",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_gpu_clock_mhz{instance=\"$instance\"} * 10000000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GPU Load %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ohm_gpu_load_percent{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ohm_gpu_temperature_celsius{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Load %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ohm_gpu_memory_load_percent{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Clock Speed",
   "type": "graph",
   "description": "Current frequency of memory clock.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "ohm_gpu_memory_clock_mhz{instance=~\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "graph",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "ohm_gpu_power_watts{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "graph",
   "description": "The fan speed value is the percent of the product's maximum noise tolerance fan speed that the device's fan is currently intended to run at. This value may exceed 100% in certain cases. Note: The reported speed is the intended fan speed. If the fan is physically blocked and unable to spin, this output will not match the actual fan speed. Many parts do not report fan speeds because they rely on cooling via fans in the surrounding enclosure.\n",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 62 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ohm_gpu_fan_percent{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Allocation (Nvidia Only)",
   "type": "graph",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "ohm_gpu_memory_used_bytes{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Graphics Clock Speed",
   "type": "graph",
   "description": "Current frequency of graphics (shader) clock.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "ohm_gpu_clock_mhz{instance=\"$instance\",name=~\".*Core.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Graphics Throughput (Nvidia Only)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "ohm_gpu_throughput_bytes_per_seconds{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Mainboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Fan: $fanname",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4.8, "x": 0, "y": 74 },
   "repeat": "fanname",
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_mainboard_lpc_fan_rpm{instance=\"$instance\",name=~\"$fanname\"}",
     "legendFormat": "[{{parent_name}}] {{name}}"
    }
   ]
  },
  {
   "title": "Fan: $fanname",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4.8, "x": 0, "y": 79 },
   "repeat": "fanname",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_mainboard_lpc_fan_percent{instance=\"$instance\",name=~\"$fanname\"}",
     "legendFormat": "[{{parent_name}}] {{name}}"
    }
   ]
  },
  {
   "title": "Mainboard Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ohm_mainboard_lpc_temperature_celsius{instance=\"$instance\"}",
     "legendFormat": "[{{parent_name}}] {{name}}"
    }
   ]
  },
  {
   "title": "Fan RPM",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    {
     "expr": "ohm_mainboard_lpc_fan_rpm{instance=\"$instance\"}",
     "legendFormat": "[{{parent_name}}] {{name}}"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ohm_mainboard_lpc_fan_percent{instance=\"$instance\"}",
     "legendFormat": "[{{parent_name}}] {{name}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ohm_mainboard_lpc_volts{instance=\"$instance\"}",
     "legendFormat": "[{{parent_name}}] {{name}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "Memory Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ohm_memory_load_percent{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "ohm_memory_used_bytes{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "$parent_identifier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 }, "repeat": "parent_identifier" },
  {
   "title": "Name",
   "type": "stat",
   "description": "The official product name of the GPU. This is an alphanumeric string. For all products.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ohm_disk_temperature_celsius{instance=\"$instance\",parent_identifier=\"$parent_identifier\"}",
     "legendFormat": "{{parent_name}}"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 130 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ohm_disk_temperature_celsius{instance=\"$instance\",parent_identifier=\"$parent_identifier\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "ohm_disk_load_percent{instance=\"$instance\",parent_identifier=\"$parent_identifier\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk Written Bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "ohm_disk_written_bytes{instance=\"$instance\",parent_identifier=\"$parent_identifier\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk Remaining Life",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_disk_remaining_life_percent{instance=\"$instance\",parent_identifier=\"$parent_identifier\"}"
    }
   ]
  },
  {
   "title": "Disk Write Amplification",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ohm_disk_write_amplification_total{instance=\"$instance\",parent_identifier=\"$parent_identifier\"}"
    }
   ]
  }
 ]
}